name: Create hosts
description: create hosts mapping to input ip
author: Kamontat Chantrachirathumrong

inputs:
  domains:
    description: list of host string separated by comma or new-line
    required: true
  ip:
    description: target ip-address
    default: 127.0.0.1
  dryrun:
    description: dry-run the command instead executes
    required: false

# outputs:
#   output:
#     description: Output description

runs:
  using: node20
  main: index.js
  post: post.js
