name: Set up asdf
description: Set up asdf and install tools based on .tool-versions file
author: Kamontat Chantrachirathumrong

inputs:
  ref:
    description: asdf reference to install
    default: master
  asdfdir:
    description: a directory where asdf should be
    required: false
  workdir:
    description: all commands will run from this directory
    default: ${{ github.workspace }}
  tool-install:
    description: install tool based from .tool-versions file
    default: "false"
  cache-disabled:
    description: for disable both asdf and tools cache (if applied)
    default: "false"
  cache-key:
    description: cache key for invalidate cache
    default: ""
  dryrun:
    description: dry-run the command instead executes
    required: false

# outputs:
#   output:
#     description: Output description

runs:
  using: node20
  pre: pre.js
  main: index.js
  post-if: success()
  post: post.js
