name: Test

on:
  push:

jobs:
  test-example:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v4
      - name: with default name
        uses: kc-workspace/github-actions/example-ts@main
      - name: '[with] custom name'
        uses: kc-workspace/github-actions/example-ts@main
        with:
          name: custom
      - name: '[env] custom name [action specific]'
        uses: kc-workspace/github-actions/example-ts@main
        env:
          EXAMPLE_TS__NAME: action-specific
      - name: '[env] custom name [generic name]'
        uses: kc-workspace/github-actions/example-ts@main
        env:
          NAME: generic-name
  test-asdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v4
      - name: with default value
        uses: kc-workspace/github-actions/setup-asdf@main
      - name: with tools enabled
        uses: kc-workspace/github-actions/setup-asdf@main
        with:
          workdir: .github/tests/setup-asdf
          install-tools: true
  test-create-hosts-dryrun:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v4
      - uses: kc-workspace/github-actions/create-hosts@main
        with:
          domains: runner.com
          dryrun: true
      - uses: kc-workspace/github-actions/create-hosts@main
        with:
          domains: runner.com
        env:
          DRYRUN: true
      - uses: kc-workspace/github-actions/create-hosts@main
        with:
          domains: runner.com
        env:
          CREATE_HOSTS__DRYRUN: true
  test-create-hosts:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v4
      - uses: kc-workspace/github-actions/create-hosts@main
        with:
          domains: example.com,hello-world.com
      - run: docker run --name nginx --rm --publish 9999:80 --detach nginx:stable
      - run: curl -I "example.com:9999"
      - run: curl -I "hello-world.com:9999"
      - run: docker stop nginx
